name: 'Validate Terraform files'

on:
  pull_request:

defaults:
  run:
    shell: bash
    working-directory: ./IaC/

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.1.7"

    - name: init
      run: terraform init

    - name: validate
      run: terraform validate

